/**
 * Independent Validation Lab — Phase 7 a11y / CWS claims probes.
 * Honesty of listing claims + WCAG surface markers. No product feature work.
 */

import { afterEach, describe, expect, it } from 'vitest';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import axe from 'axe-core';
import { InterceptDecision } from '@sentinel-shield/shared-types';
import { DecisionOverlay } from './ui/overlay.js';
import { t } from './ui/i18n.js';
import type { SentinelOptions } from './ui/options-app.js';
import './ui/options-app.js';

const extRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(extRoot, '..', '..');
const storeRoot = join(repoRoot, 'store');

const FORBIDDEN_ABSOLUTE = [
  'blocks all leaks',
  'prevents all AI exfiltration',
  'full clipboard firewall',
  'undetectable',
  '100% accuracy',
] as const;

afterEach(() => {
  document.querySelectorAll('sentinel-shield-overlay').forEach((n) => n.remove());
  document.querySelectorAll('sentinel-options').forEach((n) => n.remove());
});

describe('Lab P7 — G4 listing / claims honesty', () => {
  it('listing + attestation omit absolute capability claims outside Forbidden section', () => {
    for (const name of ['CWS_LISTING.md', 'CWS_PACKAGE_ATTESTATION.md', 'BETA_CHECKLIST.md']) {
      expect(existsSync(join(storeRoot, name)), name).toBe(true);
    }
    const listing = readFileSync(join(storeRoot, 'CWS_LISTING.md'), 'utf8').toLowerCase();
    const body = listing.split('## forbidden phrases')[0] ?? listing;
    for (const phrase of FORBIDDEN_ABSOLUTE) {
      expect(body.includes(phrase), phrase).toBe(false);
    }
    expect(listing).toMatch(/local privacy assistant/);
    expect(listing).toMatch(/on-device|locally/);
    expect(listing).toMatch(/clipboard\.readtext|navigator\.clipboard/);
    expect(listing).toMatch(/fail(?:s)? closed/);
  });

  it('CERTIFICATION_STATUS keeps G4 PASS without authorizing CWS publish', () => {
    const status = JSON.parse(
      readFileSync(join(storeRoot, 'CERTIFICATION_STATUS.json'), 'utf8'),
    ) as {
      gates: Record<string, string>;
      authorizesCwsPublish: boolean;
      publicProductionVerdict: string;
    };
    expect(status.gates['G4_claims']).toBe('PASS');
    expect(status.authorizesCwsPublish).toBe(false);
    expect(status.publicProductionVerdict).toBe('NO_GO');
  });

  it('i18n messages stay within CWS description limit and resolve actions', () => {
    const messages = JSON.parse(
      readFileSync(join(extRoot, '_locales', 'en', 'messages.json'), 'utf8'),
    ) as Record<string, { message: string }>;
    expect(messages['extensionDescription']!.message.length).toBeLessThanOrEqual(132);
    expect(t('action_allow')).toBeTruthy();
    expect(t('action_block')).toBeTruthy();
    expect(t('action_redact')).toBeTruthy();
    expect(t('extensionName')).toMatch(/Sentinel Shield/);
  });
});

describe('Lab P7 — a11y decision variants + options axe', () => {
  it('REDACT decision exposes dialog and more than one action', () => {
    const overlay = new DecisionOverlay();
    overlay.show({
      outcome: {
        interceptId: 'lab-redact',
        decision: InterceptDecision.REDACT,
        reason: 'Redact secrets',
        redactedText: '[REDACTED]',
        preview: 'sk-***',
      },
      onAction: () => undefined,
    });
    const snap = overlay.getA11ySnapshotForTests();
    expect(snap.role).toBe('dialog');
    expect(snap.ariaModal).toBe('true');
    expect(overlay.getFocusableCountForTests()).toBeGreaterThanOrEqual(2);
    overlay.hide();
  });

  it('options surface has no serious/critical axe violations (WCAG 2.1 AA tags)', async () => {
    const el = document.createElement('sentinel-options') as SentinelOptions;
    document.body.appendChild(el);
    await el.updateComplete;
    el.error = '';
    el.message = '';
    await el.updateComplete;
    const results = await axe.run(el, {
      runOnly: { type: 'tag', values: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'] },
    });
    const bad = results.violations.filter((v) => v.impact === 'serious' || v.impact === 'critical');
    expect(bad, JSON.stringify(bad, null, 2)).toEqual([]);
  });
});

describe('Lab P7 — store assets residual (KI-017)', () => {
  it('documents engineering screenshots as fixtures; promo quality remains soft residual', () => {
    const assets = join(storeRoot, 'assets');
    expect(existsSync(join(assets, 'README.md'))).toBe(true);
    const readme = readFileSync(join(assets, 'README.md'), 'utf8').toLowerCase();
    expect(readme).toMatch(/screenshot|promo|engineering/);
    const pngs = existsSync(assets) ? readdirSync(assets).filter((n) => n.endsWith('.png')) : [];
    // Soft: PNGs may be generated by e2e; if present, expect popup+options pair.
    if (pngs.length > 0) {
      expect(pngs.some((n) => n.includes('popup'))).toBe(true);
      expect(pngs.some((n) => n.includes('options'))).toBe(true);
    }
    const known = readFileSync(join(repoRoot, 'KNOWN_ISSUES.md'), 'utf8');
    expect(known).toMatch(/KI-017/);
  });
});
