/** AI provider + messaging + payment API detectors. */

import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const AI_MESSAGING_PAY_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'openai.api_key',
    name: 'OpenAI API key (sk-)',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`\bsk-[A-Za-z0-9]{20,}\b`,
    confidence: 0.9,
    sourceRef: 'OpenAI secret key prefix sk- (also overlaps some other vendors)',
    regexJustification: 'Historical OpenAI sk- keys; may overlap DeepSeek-style sk-',
    expectedFalsePositives: 'Other vendors using sk-; short demo strings meeting length',
    expectedFalseNegatives: 'Project keys with sk-proj- still match; entirely new prefixes',
    positiveExamples: ['sk-abcdefghijklmnopqrstuvwxyz123456'],
    negativeExamples: ['sk-short'],
  }),
  spec({
    id: 'openai.project_key',
    name: 'OpenAI project key (sk-proj-)',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`\bsk-proj-[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.94,
    sourceRef: 'OpenAI project API key prefix',
    regexJustification: 'More specific than bare sk-',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy sk- only keys (covered elsewhere)',
    positiveExamples: ['sk-proj-abcdefghijklmnopqrstuvwx'],
  }),
  spec({
    id: 'openai.svcacct',
    name: 'OpenAI service account key (sk-svcacct-)',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`\bsk-svcacct-[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'OpenAI service account key prefix',
    regexJustification: 'Distinct sk-svcacct- prefix',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Rotated naming',
    positiveExamples: ['sk-svcacct-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'anthropic.api_key',
    name: 'Anthropic API key (sk-ant-)',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`\bsk-ant-[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.96,
    sourceRef: 'Anthropic API key prefix sk-ant-',
    regexJustification: 'Vendor-specific prefix',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Future prefix changes',
    positiveExamples: ['sk-ant-api03-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'google.ai_studio_key',
    name: 'Google AI Studio / Gemini key (AIza)',
    category: 'ai_provider',
    severity: 'high',
    pattern: String.raw`\bAIza[0-9A-Za-z\-_]{35}\b`,
    confidence: 0.9,
    sourceRef: 'Same AIza family as GCP API keys',
    regexJustification: 'Shared Google key namespace',
    expectedFalsePositives: 'Browser-restricted keys',
    expectedFalseNegatives: 'Non-AIza Gemini auth',
    positiveExamples: ['AIzaSyB-abcdefghijklmnopqrstuvwxyz01234'],
  }),
  spec({
    id: 'groq.api_key',
    name: 'Groq API key (gsk_)',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`\bgsk_[A-Za-z0-9]{20,}\b`,
    confidence: 0.94,
    sourceRef: 'Groq API key prefix gsk_',
    regexJustification: 'gsk_ prefix',
    expectedFalsePositives: 'Unrelated gsk_ codes',
    expectedFalseNegatives: 'Alternate auth',
    positiveExamples: ['gsk_abcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'replicate.api_token',
    name: 'Replicate API token (r8_)',
    category: 'ai_provider',
    severity: 'high',
    pattern: String.raw`\br8_[A-Za-z0-9]{20,}\b`,
    confidence: 0.9,
    sourceRef: 'Replicate API token prefix',
    regexJustification: 'r8_ prefix',
    expectedFalsePositives: 'Short r8_ IDs',
    expectedFalseNegatives: 'Other auth schemes',
    positiveExamples: ['r8_abcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'slack.bot_token',
    name: 'Slack bot token (xoxb-)',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`\bxoxb-[A-Za-z0-9\-]{10,}\b`,
    confidence: 0.95,
    sourceRef: 'Slack token prefixes',
    regexJustification: 'xoxb- bot tokens',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Granular xapp tokens only',
    positiveExamples: ['xoxb-123456789012-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'slack.user_token',
    name: 'Slack user token (xoxp-)',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`\bxoxp-[A-Za-z0-9\-]{10,}\b`,
    confidence: 0.95,
    sourceRef: 'Slack token prefixes',
    regexJustification: 'xoxp- user tokens',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'App-level tokens',
    positiveExamples: ['xoxp-123456789012-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'slack.app_token',
    name: 'Slack app token (xapp-)',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`\bxapp-[A-Za-z0-9\-]{10,}\b`,
    confidence: 0.94,
    sourceRef: 'Slack app-level tokens',
    regexJustification: 'xapp- prefix',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Legacy xoxa',
    positiveExamples: ['xapp-1-abcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'slack.webhook_url',
    name: 'Slack incoming webhook URL',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`https://hooks\.slack\.com/services/[A-Za-z0-9/_-]{20,}`,
    confidence: 0.97,
    sourceRef: 'Slack incoming webhook URL shape',
    regexJustification: 'Host-constrained webhook path',
    expectedFalsePositives: 'Very low',
    expectedFalseNegatives: 'Enterprise grid alternate hosts',
    positiveExamples: [
      'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX',
    ],
  }),
  spec({
    id: 'discord.bot_token',
    name: 'Discord bot token',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`\b[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27,}\b`,
    confidence: 0.85,
    sourceRef: 'Discord bot token three-part format (public scanner family)',
    regexJustification: 'Classic Discord token structure',
    expectedFalsePositives: 'JWT-like three-part strings starting with M/N',
    expectedFalseNegatives: 'Newer Discord token formats',
    positiveExamples: ['MDI2MzA5NTM5NTIyMzE2OTk0.Gabcd1.abcdefghijklmnopqrstuvwxyz012345'],
  }),
  spec({
    id: 'discord.webhook_url',
    name: 'Discord webhook URL',
    category: 'messaging',
    severity: 'critical',
    pattern: String.raw`https://(?:discord\.com|discordapp\.com)/api/webhooks/\d+/[A-Za-z0-9_\-]+`,
    confidence: 0.97,
    sourceRef: 'Discord webhook URL path',
    regexJustification: 'Host + /api/webhooks/',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Proxy URLs',
    positiveExamples: [
      'https://discord.com/api/webhooks/123456789012345678/abcdefghijklmnopqrstuvwxyzABCDEF',
    ],
  }),
  spec({
    id: 'twilio.account_sid',
    name: 'Twilio Account SID (AC)',
    category: 'email_sms',
    severity: 'medium',
    pattern: String.raw`\bAC[a-f0-9]{32}\b`,
    confidence: 0.8,
    sourceRef: 'Twilio Account SID format',
    regexJustification: 'AC + 32 hex — identifier; often paired with auth token',
    expectedFalsePositives: 'Other AC+hex IDs',
    expectedFalseNegatives: 'Subaccount SID variants',
    positiveExamples: [`AC${'ab'.repeat(16)}`],
  }),
  spec({
    id: 'twilio.api_key_sid',
    name: 'Twilio API key SID (SK)',
    category: 'email_sms',
    severity: 'high',
    pattern: String.raw`\bSK[a-f0-9]{32}\b`,
    confidence: 0.86,
    sourceRef: 'Twilio API Key SID',
    regexJustification: 'SK + 32 hex',
    expectedFalsePositives: 'Other SK+hex',
    expectedFalseNegatives: 'Auth tokens without SID',
    positiveExamples: [`SK${'cd'.repeat(16)}`],
  }),
  spec({
    id: 'twilio.auth_token_label',
    name: 'Twilio auth token assignment',
    category: 'email_sms',
    severity: 'critical',
    pattern: String.raw`(?:TWILIO_AUTH_TOKEN|auth_token)\s*[=:]\s*['"]?[a-f0-9]{32}`,
    confidence: 0.92,
    sourceRef: 'Twilio auth token env/docs',
    regexJustification: 'Labeled 32-hex auth token',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled tokens',
    positiveExamples: [`TWILIO_AUTH_TOKEN=${'ab'.repeat(16)}`],
  }),
  spec({
    id: 'sendgrid.api_key',
    name: 'SendGrid API key (SG.)',
    category: 'email_sms',
    severity: 'critical',
    pattern: String.raw`\bSG\.[A-Za-z0-9_\-]{16,}\.[A-Za-z0-9_\-]{16,}\b`,
    confidence: 0.95,
    sourceRef: 'SendGrid API key format SG.…',
    regexJustification: 'SG. two-segment body',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy keys',
    positiveExamples: ['SG.abcdefghijklmnopqrstuv.ABCDEFGHIJKLMNOPQRSTUV'],
  }),
  spec({
    id: 'mailgun.api_key_label',
    name: 'Mailgun API key assignment',
    category: 'email_sms',
    severity: 'critical',
    pattern: String.raw`(?:MAILGUN_API_KEY|mailgun[_-]?api[_-]?key)\s*[=:]\s*['"]?[A-Za-z0-9\-]{20,}`,
    confidence: 0.9,
    sourceRef: 'Mailgun API key env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled key-… prefixes only',
    positiveExamples: ['MAILGUN_API_KEY=key-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.secret_live',
    name: 'Stripe secret key (live)',
    category: 'payments_api',
    severity: 'critical',
    pattern: String.raw`\bsk_live_[A-Za-z0-9]{16,}\b`,
    confidence: 0.97,
    sourceRef: 'Stripe secret key prefixes',
    regexJustification: 'sk_live_ production secrets',
    expectedFalsePositives: 'Stripe test fixtures in docs (still sensitive-shaped)',
    expectedFalseNegatives: 'Restricted keys rk_live_',
    positiveExamples: ['sk_live_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.secret_test',
    name: 'Stripe secret key (test)',
    category: 'payments_api',
    severity: 'high',
    pattern: String.raw`\bsk_test_[A-Za-z0-9]{16,}\b`,
    confidence: 0.95,
    sourceRef: 'Stripe test secret keys',
    regexJustification: 'sk_test_',
    expectedFalsePositives: 'Published test keys in samples',
    expectedFalseNegatives: 'Live keys',
    positiveExamples: ['sk_test_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.restricted_live',
    name: 'Stripe restricted key (live)',
    category: 'payments_api',
    severity: 'critical',
    pattern: String.raw`\brk_live_[A-Za-z0-9]{16,}\b`,
    confidence: 0.96,
    sourceRef: 'Stripe restricted API keys',
    regexJustification: 'rk_live_',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'sk_live only pastes',
    positiveExamples: ['rk_live_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.restricted_test',
    name: 'Stripe restricted key (test)',
    category: 'payments_api',
    severity: 'high',
    pattern: String.raw`\brk_test_[A-Za-z0-9]{16,}\b`,
    confidence: 0.94,
    sourceRef: 'Stripe restricted test keys',
    regexJustification: 'rk_test_',
    expectedFalsePositives: 'Samples',
    expectedFalseNegatives: 'Other stripe key classes',
    positiveExamples: ['rk_test_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.publishable_live',
    name: 'Stripe publishable key (live)',
    category: 'payments_api',
    severity: 'medium',
    pattern: String.raw`\bpk_live_[A-Za-z0-9]{16,}\b`,
    confidence: 0.9,
    sourceRef: 'Stripe publishable keys (client-side; still environment identifiers)',
    regexJustification: 'pk_live_ — lower severity than secrets',
    expectedFalsePositives: 'Intentionally public in browsers',
    expectedFalseNegatives: 'N/A',
    positiveExamples: ['pk_live_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'stripe.webhook_secret',
    name: 'Stripe webhook signing secret',
    category: 'payments_api',
    severity: 'critical',
    pattern: String.raw`\bwhsec_[A-Za-z0-9]{16,}\b`,
    confidence: 0.97,
    sourceRef: 'Stripe webhook signing secret prefix',
    regexJustification: 'whsec_',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Custom webhook auth',
    positiveExamples: ['whsec_abcdefghijklmnopqrstuv'],
  }),
];
