/** AWS / Azure / GCP credential detectors. */

import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const CLOUD_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'aws.access_key_id',
    name: 'AWS access key ID (AKIA)',
    category: 'cloud_aws',
    severity: 'critical',
    pattern: String.raw`\bAKIA[0-9A-Z]{16}\b`,
    confidence: 0.95,
    sourceRef: 'AWS IAM access key ID format (AKIA…)',
    regexJustification: 'Fixed AKIA + 16 uppercase alnum — vendor-stable prefix',
    expectedFalsePositives: 'Documented example keys in AWS docs (still sensitive-shaped)',
    expectedFalseNegatives: 'ASIA temporary keys (separate detector), obfuscated splits',
    positiveExamples: ['AKIAIOSFODNN7EXAMPLE'],
    negativeExamples: ['AKIA_SHORT'],
  }),
  spec({
    id: 'aws.access_key_id_asia',
    name: 'AWS temporary access key ID (ASIA)',
    category: 'cloud_aws',
    severity: 'critical',
    pattern: String.raw`\bASIA[0-9A-Z]{16}\b`,
    confidence: 0.93,
    sourceRef: 'AWS STS temporary key IDs',
    regexJustification: 'ASIA prefix mirrors AKIA width',
    expectedFalsePositives: 'Training fixtures using ASIA…EXAMPLE',
    expectedFalseNegatives: 'Non-standard STS issuers',
    positiveExamples: ['ASIAIOSFODNN7EXAMPLE'],
  }),
  spec({
    id: 'aws.secret_access_key',
    name: 'AWS secret access key (40-char)',
    category: 'cloud_aws',
    severity: 'critical',
    pattern: String.raw`(?<![A-Za-z0-9/+=])(?=[A-Za-z0-9/+=]*[/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=])`,
    confidence: 0.55,
    entropyPolicy: 'min_4_5',
    sourceRef: 'AWS secret key length/charset; entropy-gated; requires /+= (Phase C FP harden)',
    regexJustification:
      'Exact 40-char AWS secret alphabet; requires at least one /+= to cut pure alnum FPs',
    expectedFalsePositives: 'Random 40-char tokens that include /+= and high entropy',
    expectedFalseNegatives: 'Secrets with unusual charset; pure alnum AWS secrets (rare)',
    positiveExamples: ['wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'],
  }),
  spec({
    id: 'aws.session_token_hint',
    name: 'AWS session token assignment hint',
    category: 'cloud_aws',
    severity: 'high',
    pattern: String.raw`(?:AWS_SESSION_TOKEN|aws_session_token)\s*[=:]\s*['"]?[A-Za-z0-9/+=]{20,}`,
    confidence: 0.88,
    sourceRef: 'AWS CLI/env credential file field names',
    regexJustification: 'Labeled assignment reduces FP vs bare base64',
    expectedFalsePositives: 'Fake .env examples in tutorials',
    expectedFalseNegatives: 'Unlabeled pasted session tokens',
    positiveExamples: ['AWS_SESSION_TOKEN=FwoGZXIvYXdzEXampleSessionTokenValue123456'],
  }),
  spec({
    id: 'azure.storage_account_key_label',
    name: 'Azure storage account key (labeled)',
    category: 'cloud_azure',
    severity: 'critical',
    pattern: String.raw`AccountKey=([A-Za-z0-9+/=]{40,})`,
    confidence: 0.9,
    sourceRef: 'Azure Storage connection string AccountKey=',
    regexJustification: 'Labeled key in connection string — high precision',
    expectedFalsePositives: 'Docs using placeholder AccountKey=xxx…',
    expectedFalseNegatives: 'Keys pasted without AccountKey= label',
    positiveExamples: [
      'DefaultEndpointsProtocol=https;AccountName=ex;AccountKey=abcdefghijklmnopqrstuvwxyz0123456789ABCD+/=;EndpointSuffix=core.windows.net',
    ],
  }),
  spec({
    id: 'azure.sas_signature',
    name: 'Azure SAS signature parameter',
    category: 'cloud_azure',
    severity: 'high',
    pattern: String.raw`[?&]sig=[A-Za-z0-9%/+]{20,}`,
    confidence: 0.8,
    sourceRef: 'Azure Shared Access Signature query parameter sig=',
    regexJustification: 'sig= query param common to SAS URLs',
    expectedFalsePositives: 'Non-Azure URLs using sig= tracking params',
    expectedFalseNegatives: 'SAS with unusual encoding',
    positiveExamples: [
      'https://ex.blob.core.windows.net/c?sv=2021-08-06&sig=abcdefABCDEF0123456789%2F%2B',
    ],
  }),
  spec({
    id: 'azure.client_secret_label',
    name: 'Azure AD client secret assignment',
    category: 'cloud_azure',
    severity: 'critical',
    pattern: String.raw`(?:AZURE_CLIENT_SECRET|client_secret)\s*[=:]\s*['"]?[A-Za-z0-9~._-]{16,}`,
    confidence: 0.86,
    sourceRef: 'Azure identity env vars / OAuth client_secret field',
    regexJustification: 'Labeled secret assignment',
    expectedFalsePositives: 'Sample .env in READMEs',
    expectedFalseNegatives: 'Portal-only secrets without labels',
    positiveExamples: ['AZURE_CLIENT_SECRET=abc~DEF.0123456789_secret'],
  }),
  spec({
    id: 'gcp.api_key_aiza',
    name: 'Google/GCP API key (AIza)',
    category: 'cloud_gcp',
    severity: 'high',
    pattern: String.raw`\bAIza[0-9A-Za-z\-_]{35}\b`,
    confidence: 0.92,
    sourceRef: 'Google API key prefix AIza…',
    regexJustification: 'Vendor prefix + fixed remaining length',
    expectedFalsePositives: 'Public browser keys restricted by referrer (still secrets-ish)',
    expectedFalseNegatives: 'Newer Google key formats without AIza',
    positiveExamples: ['AIzaSyA-abcdefghijklmnopqrstuvwxyz01234'],
  }),
  spec({
    id: 'gcp.service_account_private_key_block',
    name: 'GCP service account private_key PEM in JSON',
    category: 'cloud_gcp',
    severity: 'critical',
    pattern: String.raw`"private_key"\s*:\s*"-----BEGIN (?:RSA )?PRIVATE KEY-----`,
    confidence: 0.97,
    sourceRef: 'GCP service account JSON key file schema',
    regexJustification: 'JSON field + PEM header co-occurrence',
    expectedFalsePositives: 'Documented redacted examples still containing header',
    expectedFalseNegatives: 'Keys outside JSON / escaped differently',
    positiveExamples: ['{"private_key": "-----BEGIN PRIVATE KEY-----\\nMIIE'],
  }),
  spec({
    id: 'gcp.firebase_legacy_server_key_label',
    name: 'Firebase/FCM server key label',
    category: 'cloud_gcp',
    severity: 'high',
    pattern: String.raw`(?:firebase[_-]?server[_-]?key|FCM_SERVER_KEY)\s*[=:]\s*['"]?[A-Za-z0-9:_-]{20,}`,
    confidence: 0.84,
    sourceRef: 'Legacy FCM server key configuration labels',
    regexJustification: 'Labeled assignment for FCM/Firebase server keys',
    expectedFalsePositives: 'Tutorial placeholders',
    expectedFalseNegatives: 'Unlabeled key material',
    positiveExamples: ['FCM_SERVER_KEY=AAAAabcdefghijklmnopqrstuv:APA91bExampleServerKeyValue'],
  }),
];
