/** Database URIs, crypto material, auth tokens, containers, IAC, SaaS. */

import { EntityType } from '@sentinel-shield/shared-types';
import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const DATA_CRYPTO_SAAS_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'db.mongodb_uri',
    name: 'MongoDB connection URI',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`mongodb(?:\+srv)?://[^\s'"]+`,
    confidence: 0.93,
    sourceRef: 'MongoDB Connection String URI format',
    regexJustification: 'Scheme-gated URI capture',
    expectedFalsePositives: 'URIs with placeholders user:pass@host',
    expectedFalseNegatives: 'Split across lines',
    positiveExamples: ['mongodb+srv://user:p4ssw0rd@cluster0.example.mongodb.net/db'],
  }),
  spec({
    id: 'db.postgres_uri',
    name: 'PostgreSQL connection URI',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`postgres(?:ql)?://[^\s'"]+`,
    confidence: 0.93,
    sourceRef: 'libpq URI format',
    regexJustification: 'postgres:// / postgresql:// schemes',
    expectedFalsePositives: 'Docs with fake credentials',
    expectedFalseNegatives: 'JDBC-only URLs',
    positiveExamples: ['postgresql://user:secret@db.example.com:5432/app'],
  }),
  spec({
    id: 'db.mysql_uri',
    name: 'MySQL connection URI',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`mysql://[^\s'"]+`,
    confidence: 0.9,
    sourceRef: 'Common mysql:// URI convention',
    regexJustification: 'Scheme gate',
    expectedFalsePositives: 'Examples',
    expectedFalseNegatives: 'JDBC mysql: only',
    positiveExamples: ['mysql://root:secret@127.0.0.1:3306/app'],
  }),
  spec({
    id: 'db.redis_uri',
    name: 'Redis connection URI',
    category: 'database',
    severity: 'high',
    pattern: String.raw`rediss?://[^\s'"]+`,
    confidence: 0.9,
    sourceRef: 'Redis URI schemes redis:// rediss://',
    regexJustification: 'Scheme gate',
    expectedFalsePositives: 'Local redis://localhost without password (still env leak signal)',
    expectedFalseNegatives: 'Host/port without URI',
    positiveExamples: ['rediss://:s3cr3t@redis.example.com:6380'],
  }),
  spec({
    id: 'db.amqp_uri',
    name: 'AMQP connection URI',
    category: 'database',
    severity: 'high',
    pattern: String.raw`amqps?://[^\s'"]+`,
    confidence: 0.9,
    sourceRef: 'AMQP URI scheme',
    regexJustification: 'amqp:// / amqps://',
    expectedFalsePositives: 'Examples',
    expectedFalseNegatives: 'Non-URI broker configs',
    positiveExamples: ['amqps://user:pass@mq.example.com/vhost'],
  }),
  spec({
    id: 'db.mssql_ado_password',
    name: 'SQL Server connection string Password=',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`(?:Password|Pwd)=([^;'"\s]{4,})`,
    confidence: 0.88,
    entityType: EntityType.PASSWORD,
    sourceRef: 'ADO.NET / ODBC connection string password keys',
    regexJustification: 'Labeled Password=/Pwd=',
    expectedFalsePositives: 'Password=; empty or Password=*** masks',
    expectedFalseNegatives: 'Integrated Security only',
    positiveExamples: ['Server=.;Database=app;User Id=sa;Password=S3cret!Value;'],
  }),
  spec({
    id: 'crypto.pem_private_key',
    name: 'PEM private key header',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`-----BEGIN (?:OPENSSH |RSA |EC |DSA |ENCRYPTED )?PRIVATE KEY-----`,
    confidence: 0.97,
    sourceRef: 'PEM / OpenSSH private key armor headers',
    regexJustification: 'BEGIN *PRIVATE KEY* headers',
    expectedFalsePositives: 'Docs showing headers only',
    expectedFalseNegatives: 'Binary DER without armor',
    positiveExamples: ['-----BEGIN OPENSSH PRIVATE KEY-----\nabc'],
  }),
  spec({
    id: 'crypto.pem_rsa_private',
    name: 'PEM RSA private key header',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`-----BEGIN RSA PRIVATE KEY-----`,
    confidence: 0.97,
    sourceRef: 'PKCS#1 PEM',
    regexJustification: 'Exact RSA PRIVATE KEY armor',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'PKCS#8 generic PRIVATE KEY only',
    positiveExamples: ['-----BEGIN RSA PRIVATE KEY-----'],
  }),
  spec({
    id: 'crypto.pem_ec_private',
    name: 'PEM EC private key header',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`-----BEGIN EC PRIVATE KEY-----`,
    confidence: 0.97,
    sourceRef: 'SEC1 PEM',
    regexJustification: 'EC PRIVATE KEY armor',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'PKCS#8 only',
    positiveExamples: ['-----BEGIN EC PRIVATE KEY-----'],
  }),
  spec({
    id: 'crypto.pem_encrypted_private',
    name: 'PEM encrypted private key header',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`-----BEGIN ENCRYPTED PRIVATE KEY-----`,
    confidence: 0.96,
    sourceRef: 'PKCS#8 encrypted PEM',
    regexJustification: 'ENCRYPTED PRIVATE KEY armor',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Password-protected OpenSSH format variants',
    positiveExamples: ['-----BEGIN ENCRYPTED PRIVATE KEY-----'],
  }),
  spec({
    id: 'crypto.pem_certificate',
    name: 'PEM certificate header',
    category: 'crypto_material',
    severity: 'medium',
    pattern: String.raw`-----BEGIN CERTIFICATE-----`,
    confidence: 0.85,
    sourceRef: 'X.509 PEM certificates (often public; still sensitive in some pastes)',
    regexJustification: 'BEGIN CERTIFICATE',
    expectedFalsePositives: 'Public certs intentionally shared',
    expectedFalseNegatives: 'DER-only',
    positiveExamples: ['-----BEGIN CERTIFICATE-----'],
  }),
  spec({
    id: 'crypto.pgp_private',
    name: 'PGP private key block',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`-----BEGIN PGP PRIVATE KEY BLOCK-----`,
    confidence: 0.97,
    sourceRef: 'OpenPGP private key armor',
    regexJustification: 'PGP PRIVATE KEY BLOCK',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Secret key packets without armor',
    positiveExamples: ['-----BEGIN PGP PRIVATE KEY BLOCK-----'],
  }),
  spec({
    id: 'auth.jwt',
    name: 'JWT (three-part compact)',
    category: 'auth_token',
    severity: 'high',
    pattern: String.raw`\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b`,
    confidence: 0.82,
    sourceRef: 'RFC 7519 compact serialization (header/payload often eyJ)',
    regexJustification: 'eyJ…eyJ…signature triple',
    expectedFalsePositives: 'Unsigned demo JWTs, documentation tokens',
    expectedFalseNegatives: 'JWE five-part, non-JSON headers',
    positiveExamples: [
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.signatureplaceholder12',
    ],
  }),
  spec({
    id: 'auth.bearer_header',
    name: 'Authorization Bearer token',
    category: 'auth_token',
    severity: 'high',
    pattern: String.raw`(?:Authorization:\s*)?Bearer\s+[A-Za-z0-9\-._~+/]+=*`,
    confidence: 0.8,
    sourceRef: 'RFC 6750 Bearer tokens',
    regexJustification: 'Bearer + token charset',
    expectedFalsePositives: 'Short Bearer demo, public samples',
    expectedFalseNegatives: 'Non-Bearer auth schemes',
    positiveExamples: ['Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.abc.def'],
  }),
  spec({
    id: 'auth.basic_url',
    name: 'Basic auth credentials in URL',
    category: 'auth_token',
    severity: 'critical',
    pattern: String.raw`[a-zA-Z][a-zA-Z0-9+.-]*://[^/\s:@]+:[^/\s:@]+@[^/\s]+`,
    confidence: 0.9,
    entityType: EntityType.PASSWORD,
    sourceRef: 'RFC 3986 userinfo in URIs',
    regexJustification: 'scheme://user:pass@host',
    expectedFalsePositives: 'URLs with tokens in userinfo that are public demos',
    expectedFalseNegatives: 'Credentials only in headers',
    positiveExamples: ['https://admin:hunter2@db.example.com/path'],
  }),
  spec({
    id: 'auth.oauth_client_secret_label',
    name: 'OAuth client_secret assignment',
    category: 'auth_token',
    severity: 'critical',
    pattern: String.raw`(?:client_secret|CLIENT_SECRET|oauth_client_secret)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{12,}`,
    confidence: 0.9,
    sourceRef: 'OAuth 2.0 client_secret field / env',
    regexJustification: 'Labeled client_secret',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled secrets',
    positiveExamples: ['client_secret=super_secret_value_1'],
  }),
  spec({
    id: 'vault.token_hvs',
    name: 'HashiCorp Vault token (hvs.)',
    category: 'iac',
    severity: 'critical',
    pattern: String.raw`\bhvs\.[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'Vault service token prefix hvs.',
    regexJustification: 'hvs. prefix',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy s. tokens only',
    positiveExamples: ['hvs.CAESIJabcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'vault.token_legacy_s',
    name: 'HashiCorp Vault legacy token (s.)',
    category: 'iac',
    severity: 'critical',
    pattern: String.raw`\bs\.[A-Za-z0-9]{20,}\b`,
    confidence: 0.7,
    entropyPolicy: 'min_4_0',
    sourceRef: 'Legacy Vault token prefix s.',
    regexJustification: 's. + body with entropy gate (higher FP risk)',
    expectedFalsePositives: 'Sentences / abbreviations after s.',
    expectedFalseNegatives: 'hvs. only environments',
    positiveExamples: ['s.abcdefghijklmnopqrstuvwxyz12'],
  }),
  spec({
    id: 'terraform.cloud_token',
    name: 'Terraform Cloud token (atac- / nO8)',
    category: 'iac',
    severity: 'critical',
    pattern: String.raw`\b(?:atac\.[A-Za-z0-9]{20,}|[A-Za-z0-9]{14}\.atlasv1\.[A-Za-z0-9\-_=]{60,})\b`,
    confidence: 0.9,
    sourceRef: 'Terraform Cloud / Enterprise API token shapes (public scanner families)',
    regexJustification: 'atac. or atlasv1 token forms',
    expectedFalsePositives: 'Low-moderate on atlasv1',
    expectedFalseNegatives: 'Team tokens with new prefixes',
    positiveExamples: ['atac.abcdefghijklmnopqrstuvwx'],
  }),
  spec({
    id: 'k8s.secret_manifest_hint',
    name: 'Kubernetes Secret manifest hint',
    category: 'container',
    severity: 'high',
    pattern: String.raw`kind:\s*Secret[\s\S]{0,200}data:`,
    flags: 'gi',
    confidence: 0.75,
    sourceRef: 'Kubernetes Secret object shape',
    regexJustification: 'kind: Secret near data: — high FP on samples; medium confidence',
    expectedFalsePositives: 'Example manifests in docs/helm charts with dummy data',
    expectedFalseNegatives: 'Secrets without data: (stringData only beyond window)',
    positiveExamples: ['apiVersion: v1\nkind: Secret\nmetadata:\n  name: x\ndata:\n  key: YWJj'],
  }),
  spec({
    id: 'docker.auth_config_hint',
    name: 'Docker config.json auth blob hint',
    category: 'container',
    severity: 'high',
    pattern: String.raw`"auths"\s*:\s*\{[\s\S]{0,400}"auth"\s*:\s*"[A-Za-z0-9+/=]{20,}"`,
    confidence: 0.88,
    sourceRef: 'Docker config.json auths.auth base64(user:pass)',
    regexJustification: 'auths + auth field co-occurrence',
    expectedFalsePositives: 'Sanitized examples',
    expectedFalseNegatives: 'credHelpers-only configs',
    positiveExamples: [
      '{"auths":{"https://index.docker.io/v1/":{"auth":"dXNlcjpwYXNzMTIzNDU2Nzg5MA=="}}}',
    ],
  }),
  spec({
    id: 'saas.datadog_api_key',
    name: 'Datadog API key assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:DD_API_KEY|DATADOG_API_KEY)\s*[=:]\s*['"]?[a-f0-9]{32}`,
    confidence: 0.92,
    sourceRef: 'Datadog API key env vars',
    regexJustification: 'Labeled 32-hex',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: [`DD_API_KEY=${'ab'.repeat(16)}`],
  }),
  spec({
    id: 'saas.datadog_app_key',
    name: 'Datadog APP key assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:DD_APP_KEY|DATADOG_APP_KEY)\s*[=:]\s*['"]?[a-f0-9]{40}`,
    confidence: 0.92,
    sourceRef: 'Datadog application key env vars',
    regexJustification: 'Labeled 40-hex',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: [`DD_APP_KEY=${'ab'.repeat(20)}`],
  }),
  spec({
    id: 'saas.sentry_dsn',
    name: 'Sentry DSN URL',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`https://[a-f0-9]{20,}@[A-Za-z0-9.-]+/(?:\d+)`,
    confidence: 0.9,
    sourceRef: 'Sentry DSN format',
    regexJustification: 'https://key@host/projectId',
    expectedFalsePositives: 'Other key@host URLs',
    expectedFalseNegatives: 'DSN without https',
    positiveExamples: ['https://abcdef0123456789abcd@o0.ingest.sentry.io/1'],
  }),
  spec({
    id: 'saas.notion_token',
    name: 'Notion integration token (secret_/ntn_)',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`\b(?:secret_[A-Za-z0-9]{40,}|ntn_[A-Za-z0-9]{40,})\b`,
    confidence: 0.93,
    sourceRef: 'Notion internal integration token prefixes',
    regexJustification: 'secret_ / ntn_ long bodies',
    expectedFalsePositives: 'Generic secret_ labels with long random',
    expectedFalseNegatives: 'OAuth tokens without prefix',
    positiveExamples: [`secret_${'a'.repeat(43)}`],
  }),
  spec({
    id: 'saas.shopify_token',
    name: 'Shopify access token (shpat_/shpca_/shppa_)',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`\b(?:shpat_|shpca_|shppa_|shpss_)[A-Za-z0-9]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'Shopify Admin API token prefixes',
    regexJustification: 'shpat_/shpca_/shppa_/shpss_',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy tokens',
    positiveExamples: ['shpat_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'saas.cloudflare_api_token_label',
    name: 'Cloudflare API token assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:CLOUDFLARE_API_TOKEN|CF_API_TOKEN)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{20,}`,
    confidence: 0.9,
    sourceRef: 'Cloudflare API token env names',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Global API key email+key pairs unlabeled',
    positiveExamples: ['CLOUDFLARE_API_TOKEN=abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'saas.supabase_service_role',
    name: 'Supabase service role JWT-like key label',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:SUPABASE_SERVICE_ROLE_KEY|service_role)\s*[=:]\s*['"]?eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+`,
    confidence: 0.94,
    sourceRef: 'Supabase service_role JWT env',
    regexJustification: 'Labeled JWT assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled JWT paste (covered by auth.jwt)',
    positiveExamples: [
      'SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIn0.sig',
    ],
  }),
  spec({
    id: 'saas.vercel_token',
    name: 'Vercel token assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:VERCEL_TOKEN|vercel[_-]?token)\s*[=:]\s*['"]?[A-Za-z0-9]{20,}`,
    confidence: 0.9,
    sourceRef: 'Vercel token env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['VERCEL_TOKEN=abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'saas.netlify_token',
    name: 'Netlify token assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:NETLIFY_AUTH_TOKEN|netlify[_-]?auth[_-]?token)\s*[=:]\s*['"]?[A-Za-z0-9\-_]{20,}`,
    confidence: 0.9,
    sourceRef: 'Netlify auth token env',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['NETLIFY_AUTH_TOKEN=abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'saas.heroku_api_key_label',
    name: 'Heroku API key assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:HEROKU_API_KEY|heroku[_-]?api[_-]?key)\s*[=:]\s*['"]?[A-Fa-f0-9\-]{20,}`,
    confidence: 0.9,
    sourceRef: 'Heroku API key env',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled UUID keys',
    positiveExamples: ['HEROKU_API_KEY=a1b2c3d4-e5f6-7890-abcd-ef1234567890'],
  }),
  spec({
    id: 'saas.okta_api_token_label',
    name: 'Okta API token assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:OKTA_API_TOKEN|okta[_-]?api[_-]?token)\s*[=:]\s*['"]?[A-Za-z0-9]{20,}`,
    confidence: 0.9,
    sourceRef: 'Okta API token env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'SSWS header-only pastes',
    positiveExamples: ['OKTA_API_TOKEN=abcdefghijklmnopqrstuv001122'],
  }),
  spec({
    id: 'saas.okta_ssws',
    name: 'Okta SSWS authorization token',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`SSWS\s+[A-Za-z0-9_\-]{20,}`,
    confidence: 0.93,
    sourceRef: 'Okta SSWS auth scheme',
    regexJustification: 'SSWS + token',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Bearer-only Okta',
    positiveExamples: ['SSWS abcdefghijklmnopqrstuvwxyz0123'],
  }),
  spec({
    id: 'saas.age_secret_key',
    name: 'age secret key',
    category: 'crypto_material',
    severity: 'critical',
    pattern: String.raw`AGE-SECRET-KEY-1[A-Z0-9]{58,}`,
    confidence: 0.97,
    sourceRef: 'age encryption secret key bech32-like format',
    regexJustification: 'AGE-SECRET-KEY-1 prefix',
    expectedFalsePositives: 'Very low',
    expectedFalseNegatives: 'Passphrase-wrapped keys',
    positiveExamples: [`AGE-SECRET-KEY-1${'A'.repeat(58)}`],
  }),
];
