/** Additional SaaS / cloud / developer secret detectors to complete research coverage. */

import { EntityType } from '@sentinel-shield/shared-types';
import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const EXTRA_SECRET_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'aws.secret_key_label',
    name: 'AWS secret key labeled assignment',
    category: 'cloud_aws',
    severity: 'critical',
    pattern: String.raw`(?:AWS_SECRET_ACCESS_KEY|aws_secret_access_key)\s*[=:]\s*['"]?[A-Za-z0-9/+=]{40}`,
    confidence: 0.96,
    sourceRef: 'AWS credential file / env var names',
    regexJustification: 'Labeled 40-char secret — higher precision than bare 40-char',
    expectedFalsePositives: 'Tutorial .env examples',
    expectedFalseNegatives: 'Unlabeled secrets (see aws.secret_access_key)',
    positiveExamples: ['AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'],
  }),
  spec({
    id: 'gcp.oauth_client_secret_json',
    name: 'Google OAuth client_secret JSON field',
    category: 'cloud_gcp',
    severity: 'critical',
    pattern: String.raw`"client_secret"\s*:\s*"[A-Za-z0-9\-_]{10,}"`,
    confidence: 0.9,
    sourceRef: 'Google OAuth client JSON',
    regexJustification: 'JSON client_secret field',
    expectedFalsePositives: 'Public OAuth client configs with restricted secrets',
    expectedFalseNegatives: 'YAML configs',
    positiveExamples: ['"client_secret": "GOCSPX-abcdefghijklmnopqrstuv"'],
  }),
  spec({
    id: 'azure.cosmos_key_label',
    name: 'Azure Cosmos DB key assignment',
    category: 'cloud_azure',
    severity: 'critical',
    pattern: String.raw`(?:COSMOS(?:DB)?_(?:KEY|PRIMARY_KEY)|AccountKey)\s*[=:]\s*['"]?[A-Za-z0-9+/=]{40,}`,
    confidence: 0.9,
    sourceRef: 'Azure Cosmos connection metadata',
    regexJustification: 'Labeled long base64-ish keys',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Portal copy without labels',
    positiveExamples: [`COSMOS_KEY=${'A'.repeat(44)}=`],
  }),
  spec({
    id: 'elastic.cloud_api_key',
    name: 'Elastic Cloud API key assignment',
    category: 'database',
    severity: 'high',
    pattern: String.raw`(?:ELASTIC_API_KEY|ES_API_KEY)\s*[=:]\s*['"]?[A-Za-z0-9=]{20,}`,
    confidence: 0.88,
    sourceRef: 'Elasticsearch API key env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Base64 id:api_key unlabeled pairs',
    positiveExamples: ['ELASTIC_API_KEY=dXNlcm5hbWU6cGFzc3dvcmQxMjM0NTY='],
  }),
  spec({
    id: 'square.access_token',
    name: 'Square access token (sq0atp-)',
    category: 'payments_api',
    severity: 'critical',
    pattern: String.raw`\bsq0atp-[A-Za-z0-9_\-]{10,}\b`,
    confidence: 0.95,
    sourceRef: 'Square access token prefix',
    regexJustification: 'sq0atp-',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Sandbox variants',
    positiveExamples: ['sq0atp-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'square.oauth_secret',
    name: 'Square OAuth secret (sq0csp-)',
    category: 'payments_api',
    severity: 'critical',
    pattern: String.raw`\bsq0csp-[A-Za-z0-9_\-]{10,}\b`,
    confidence: 0.95,
    sourceRef: 'Square OAuth client secret prefix',
    regexJustification: 'sq0csp-',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Other Square creds',
    positiveExamples: ['sq0csp-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'paypal.braintree_tokens',
    name: 'PayPal/Braintree access token hint',
    category: 'payments_api',
    severity: 'high',
    pattern: String.raw`access_token\$production\$[A-Za-z0-9]{10,}\$[A-Za-z0-9]{10,}`,
    confidence: 0.94,
    sourceRef: 'PayPal/Braintree access_token$production$… format',
    regexJustification: 'Distinct production access_token pattern',
    expectedFalsePositives: 'Very low',
    expectedFalseNegatives: 'Sandbox tokens',
    positiveExamples: ['access_token$production$abcdefghij$klmnopqrst'],
  }),
  spec({
    id: 'postman.api_key',
    name: 'Postman API key (PMAK-)',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`\bPMAK-[A-Za-z0-9\-]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'Postman API key prefix PMAK-',
    regexJustification: 'PMAK-',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Collection access keys with other prefixes',
    positiveExamples: ['PMAK-abcdefghijklmnopqrstuv-wxyz'],
  }),
  spec({
    id: 'linear.api_key',
    name: 'Linear API key (lin_api_)',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`\blin_api_[A-Za-z0-9]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'Linear API key prefix',
    regexJustification: 'lin_api_',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'OAuth only',
    positiveExamples: ['lin_api_abcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'asana.pat_label',
    name: 'Asana PAT assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:ASANA_ACCESS_TOKEN|asana[_-]?pat)\s*[=:]\s*['"]?[0-9]/[A-Za-z0-9]{16,}`,
    confidence: 0.9,
    sourceRef: 'Asana personal access token shape',
    regexJustification: 'Labeled 1/… or 2/… tokens',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['ASANA_ACCESS_TOKEN=1/abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'grafana.api_key',
    name: 'Grafana API key / service account (glsa_)',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`\bglsa_[A-Za-z0-9_]{20,}\b`,
    confidence: 0.9,
    sourceRef: 'Grafana service account token prefix glsa_',
    regexJustification: 'glsa_ prefix',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy eyJrIjoi keys',
    positiveExamples: ['glsa_abcdefghijklmnopqrstuvwxyz_abcde'],
  }),
  spec({
    id: 'newrelic.insert_key',
    name: 'New Relic insert/license key assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:NEW_RELIC_LICENSE_KEY|NEW_RELIC_INSERT_KEY|NR_LICENSE_KEY)\s*[=:]\s*['"]?[A-Fa-f0-9]{32,40}`,
    confidence: 0.9,
    sourceRef: 'New Relic license/insert key env vars',
    regexJustification: 'Labeled hex keys',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: [`NEW_RELIC_LICENSE_KEY=${'a'.repeat(40)}`],
  }),
  spec({
    id: 'openai.org_key_label',
    name: 'OpenAI org/project env key assignment',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`(?:OPENAI_API_KEY|OPENAI_KEY)\s*[=:]\s*['"]?sk-[A-Za-z0-9_\-]{20,}`,
    confidence: 0.97,
    sourceRef: 'OpenAI env var conventions',
    regexJustification: 'Labeled sk- assignment — highest precision OpenAI path',
    expectedFalsePositives: 'README samples',
    expectedFalseNegatives: 'Unlabeled sk- (covered by openai.api_key)',
    positiveExamples: ['OPENAI_API_KEY=sk-abcdefghijklmnopqrstuvwxyz123456'],
  }),
  spec({
    id: 'anthropic.key_label',
    name: 'Anthropic key env assignment',
    category: 'ai_provider',
    severity: 'critical',
    pattern: String.raw`(?:ANTHROPIC_API_KEY|CLAUDE_API_KEY)\s*[=:]\s*['"]?sk-ant-[A-Za-z0-9_\-]{20,}`,
    confidence: 0.97,
    sourceRef: 'Anthropic env var conventions',
    regexJustification: 'Labeled sk-ant-',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['ANTHROPIC_API_KEY=sk-ant-api03-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'dropbox.api_token',
    name: 'Dropbox API token (sl.)',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`\bsl\.[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.8,
    entropyPolicy: 'min_4_0',
    sourceRef: 'Dropbox short-lived token prefix sl. (public scanner family)',
    regexJustification: 'sl. + entropy gate',
    expectedFalsePositives: 'Words after sl.',
    expectedFalseNegatives: 'OAuth codes',
    positiveExamples: ['sl.abcdefghijklmnopqrstuvwxyz012345'],
  }),
  spec({
    id: 'facebook.access_token_label',
    name: 'Facebook/Meta access token assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:FACEBOOK_ACCESS_TOKEN|META_ACCESS_TOKEN|FB_ACCESS_TOKEN)\s*[=:]\s*['"]?[A-Za-z0-9]{20,}`,
    confidence: 0.88,
    sourceRef: 'Meta access token env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'EAA… unlabeled tokens',
    positiveExamples: ['FACEBOOK_ACCESS_TOKEN=EAAabcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'facebook.eaa_token',
    name: 'Facebook/Meta EAA access token',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`\bEAA[A-Za-z0-9]{20,}\b`,
    confidence: 0.84,
    sourceRef: 'Meta user/page token prefix EAA',
    regexJustification: 'EAA prefix long body',
    expectedFalsePositives: 'Other EAA product codes',
    expectedFalseNegatives: 'Non-EAA Meta tokens',
    positiveExamples: ['EAAabcdefghijklmnopqrstuvwxyz0123'],
  }),
  spec({
    id: 'twitter.bearer_label',
    name: 'X/Twitter bearer token assignment',
    category: 'saas',
    severity: 'high',
    pattern: String.raw`(?:TWITTER_BEARER_TOKEN|X_BEARER_TOKEN)\s*[=:]\s*['"]?[A-Za-z0-9%]{30,}`,
    confidence: 0.9,
    sourceRef: 'X API bearer env naming',
    regexJustification: 'Labeled bearer',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['TWITTER_BEARER_TOKEN=AAAAAAAAAAAAAAAA%2FAAAAAAAAAAAAAAAAAAAAAA'],
  }),
  spec({
    id: 'sendinblue_brevo.key',
    name: 'Brevo/Sendinblue API key (xkeysib-)',
    category: 'email_sms',
    severity: 'critical',
    pattern: String.raw`\bxkeysib-[A-Za-z0-9]{20,}-[A-Za-z0-9]{10,}\b`,
    confidence: 0.95,
    sourceRef: 'Brevo API key prefix xkeysib-',
    regexJustification: 'xkeysib- structured body',
    expectedFalsePositives: 'Low',
    expectedFalseNegatives: 'Legacy keys',
    positiveExamples: ['xkeysib-abcdefghijklmnopqrstuv-ABCDEFGHIJ'],
  }),
  spec({
    id: 'algolia.admin_key_label',
    name: 'Algolia admin API key assignment',
    category: 'saas',
    severity: 'critical',
    pattern: String.raw`(?:ALGOLIA_ADMIN_API_KEY|ALGOLIA_API_KEY)\s*[=:]\s*['"]?[a-f0-9]{32}`,
    confidence: 0.9,
    sourceRef: 'Algolia API key env vars',
    regexJustification: 'Labeled 32-hex (admin keys especially sensitive)',
    expectedFalsePositives: 'Search-only keys in frontend samples',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: [`ALGOLIA_ADMIN_API_KEY=${'ab'.repeat(16)}`],
  }),
  spec({
    id: 'planetscale_password_label',
    name: 'PlanetScale password assignment',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`(?:PLANETSCALE_PASSWORD|DATABASE_PASSWORD)\s*[=:]\s*['"]?(?:pscale_pw_[A-Za-z0-9_\-]{20,}|[A-Za-z0-9_\-]{16,})`,
    confidence: 0.88,
    sourceRef: 'PlanetScale / generic DB password env',
    regexJustification: 'Labeled password env including pscale_pw_',
    expectedFalsePositives: 'Generic DATABASE_PASSWORD in examples',
    expectedFalseNegatives: 'URI-embedded passwords',
    positiveExamples: ['PLANETSCALE_PASSWORD=pscale_pw_abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'snowflake_key_pair_hint',
    name: 'Snowflake private key PEM assignment hint',
    category: 'database',
    severity: 'critical',
    pattern: String.raw`(?:SNOWFLAKE_PRIVATE_KEY|snowflake[_-]?private[_-]?key)\s*[=:]\s*['"]?-----BEGIN`,
    confidence: 0.93,
    sourceRef: 'Snowflake key-pair auth configuration',
    regexJustification: 'Labeled PEM begin',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled PEM (crypto.pem_*)',
    positiveExamples: ['SNOWFLAKE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----'],
  }),
  spec({
    id: 'ldap_bind_password_label',
    name: 'LDAP bind password assignment',
    category: 'auth_token',
    severity: 'high',
    pattern: String.raw`(?:LDAP_BIND_PASSWORD|ldap[_-]?password)\s*[=:]\s*['"]?\S{6,}`,
    confidence: 0.85,
    sourceRef: 'LDAP bind password env naming',
    regexJustification: 'Labeled password',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['LDAP_BIND_PASSWORD=s3cretBindPass'],
  }),
  spec({
    id: 'generic.password_assignment',
    name: 'Generic password assignment',
    category: 'other_secret',
    severity: 'medium',
    entityType: EntityType.PASSWORD,
    pattern: String.raw`(?:password|passwd|pwd)\s*[=:]\s*['"]?[^\s'"]{8,}`,
    flags: 'gi',
    confidence: 0.55,
    sourceRef: 'Generic credential assignment heuristic (high FP — low confidence)',
    regexJustification: 'password= value — intentionally conservative confidence',
    expectedFalsePositives: 'password=******** masks, password=true flags, HTML form samples',
    expectedFalseNegatives: 'passwords without labels',
    positiveExamples: ['password=SuperSecretValue1'],
  }),
];
