/** PII + payment card / IBAN research detectors (Tier-1 legacy migrated). */

import { EntityType } from '@sentinel-shield/shared-types';
import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const PII_PAYMENT_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'pii.email',
    name: 'Email address',
    category: 'pii',
    entityType: EntityType.EMAIL,
    severity: 'low',
    pattern: String.raw`[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}`,
    confidence: 0.9,
    sourceRef: 'RFC 5322 practical subset; common DLP email heuristic',
    regexJustification: 'Local-part @ domain with TLD ≥2 — high recall paste detector',
    expectedFalsePositives: 'Synthetic emails in docs, git blame emails, noreply addresses',
    expectedFalseNegatives: 'Obfuscated (user [at] host), IDN domains without punycode',
    positiveExamples: ['alice@example.com'],
    negativeExamples: ['not-an-email@'],
  }),
  spec({
    id: 'pii.phone.us',
    name: 'US/CA phone number',
    category: 'pii',
    entityType: EntityType.PHONE,
    severity: 'medium',
    // Require separators or parentheses — contiguous 10-digit runs are order IDs / hashes (precision > recall).
    pattern: String.raw`(?<!\d)(?:\+?1[-.\s]*)?(?:\(\d{3}\)[-.\s]*|\d{3}[-.\s])\d{3}[-.\s]\d{4}(?!\d)`,
    confidence: 0.78,
    sourceRef: 'NANP formatting conventions',
    regexJustification:
      'Separators or (area) required between NANP groups; rejects raw 10-digit runs that drove hard-negative FPs',
    expectedFalsePositives: 'Hyphenated product SKUs matching ###-###-####',
    expectedFalseNegatives:
      'Unformatted 10-digit NANP, international non-NANP, extension-only lines',
    positiveExamples: ['Call +1 (415) 555-2671 now', 'Reach us at 415-555-2671'],
    negativeExamples: ['Yz0123456789', 'order id 4155552671'],
  }),
  spec({
    id: 'pii.ssn.us',
    name: 'US SSN (hyphenated)',
    category: 'pii',
    entityType: EntityType.SSN,
    severity: 'critical',
    pattern: String.raw`(?<!\d)\d{3}-\d{2}-\d{4}(?!\d)`,
    confidence: 0.85,
    sourceRef: 'SSA hyphenated presentation format',
    regexJustification: 'Strict ###-##-####; no area/group validation (avoids SSA table deps)',
    expectedFalsePositives: 'Hyphenated product codes matching shape',
    expectedFalseNegatives: 'Unhyphenated 9-digit SSN, spaced forms',
    positiveExamples: ['SSN 123-45-6789'],
  }),
  spec({
    id: 'pay.pan.continuous',
    name: 'Payment card PAN (continuous)',
    category: 'payment',
    entityType: EntityType.CREDIT_CARD,
    severity: 'critical',
    pattern: String.raw`(?<!\d)(?:4\d{12}(?:\d{3})?|5[1-5]\d{14}|3[47]\d{13}|6(?:011|5\d{2})\d{12})(?!\d)`,
    confidence: 0.7,
    sourceRef: 'ISO/IEC 7812 brand length prefixes; Luhn applied post-match',
    regexJustification: 'Visa/MC/Amex/Discover length envelopes before Luhn filter',
    expectedFalsePositives: 'Long numeric IDs that pass Luhn by chance',
    expectedFalseNegatives: 'Other schemes (unionpay denser forms), PCI-truncated already',
    positiveExamples: ['4111111111111111'],
  }),
  spec({
    id: 'pay.pan.grouped',
    name: 'Payment card PAN (grouped)',
    category: 'payment',
    entityType: EntityType.CREDIT_CARD,
    severity: 'critical',
    pattern: String.raw`(?<!\d)(?:4\d{3}|5[1-5]\d{2}|3[47]\d{2}|6(?:011|5\d{2}))(?:[-\s]?\d{4}){3}(?!\d)`,
    confidence: 0.72,
    sourceRef: 'Common paste formatting with spaces/dashes',
    regexJustification: 'Grouped 4x4 style; Luhn on digits only',
    expectedFalsePositives: 'Grouped inventory codes that Luhn-pass',
    expectedFalseNegatives: 'Amex 4-6-5 grouping variants',
    positiveExamples: ['4111 1111 1111 1111'],
  }),
  spec({
    id: 'pay.iban.compact',
    name: 'IBAN (compact)',
    category: 'payment',
    entityType: EntityType.IBAN,
    severity: 'high',
    pattern: String.raw`\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b`,
    confidence: 0.7,
    sourceRef: 'ISO 13616; MOD-97 applied post-match',
    regexJustification: 'Country + check digits + BBAN envelope',
    expectedFalsePositives: 'Random uppercase alnum matching length before MOD-97 drop',
    expectedFalseNegatives: 'Lowercase IBAN without normalize (preprocess uppercases in prepare)',
    positiveExamples: ['GB82WEST12345698765432'],
  }),
  spec({
    id: 'pay.iban.spaced',
    name: 'IBAN (spaced)',
    category: 'payment',
    entityType: EntityType.IBAN,
    severity: 'high',
    pattern: String.raw`\b[A-Z]{2}\d{2}(?:\s[A-Z0-9]{4}){2,7}(?:\s[A-Z0-9]{1,4})?\b`,
    confidence: 0.72,
    sourceRef: 'Print/electronic spaced IBAN presentation',
    regexJustification: 'Spaced 4-char groups; MOD-97 after whitespace strip',
    expectedFalsePositives: 'Spaced license keys resembling IBAN before checksum',
    expectedFalseNegatives: 'Odd grouping from OCR',
    positiveExamples: ['GB82 WEST 1234 5698 7654 32'],
  }),
];
