/** VCS / CI credential detectors. */

import { spec } from '../spec.js';
import type { DetectorSpec } from '../types.js';

export const VCS_CI_DETECTORS: readonly DetectorSpec[] = [
  spec({
    id: 'github.pat_classic',
    name: 'GitHub classic PAT (ghp_)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bghp_[A-Za-z0-9]{36}\b`,
    confidence: 0.96,
    sourceRef: 'GitHub token prefixes (ghp_)',
    regexJustification: 'ghp_ + 36 body — GitHub classic PAT',
    expectedFalsePositives: 'Synthetic tokens in vendor docs',
    expectedFalseNegatives: 'Fine-grained PATs (github_pat_)',
    positiveExamples: ['ghp_abcdefghijklmnopqrstuvwxyz0123456789'],
  }),
  spec({
    id: 'github.pat_fine_grained',
    name: 'GitHub fine-grained PAT',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bgithub_pat_[A-Za-z0-9]{22}_[A-Za-z0-9]{59}\b`,
    confidence: 0.96,
    sourceRef: 'GitHub fine-grained personal access token format',
    regexJustification: 'github_pat_ + structured body segments',
    expectedFalsePositives: 'Very rare collisions on crafted strings',
    expectedFalseNegatives: 'Format changes by GitHub',
    positiveExamples: [`github_pat_${'a'.repeat(22)}_${'b'.repeat(59)}`],
  }),
  spec({
    id: 'github.oauth_gho',
    name: 'GitHub OAuth access token (gho_)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bgho_[A-Za-z0-9]{36}\b`,
    confidence: 0.95,
    sourceRef: 'GitHub token prefix gho_',
    regexJustification: 'Same width family as ghp_',
    expectedFalsePositives: 'Doc fixtures',
    expectedFalseNegatives: 'Other GitHub app token classes',
    positiveExamples: ['gho_abcdefghijklmnopqrstuvwxyz0123456789'],
  }),
  spec({
    id: 'github.user_to_server_ghu',
    name: 'GitHub user-to-server token (ghu_)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bghu_[A-Za-z0-9]{36}\b`,
    confidence: 0.95,
    sourceRef: 'GitHub token prefix ghu_',
    regexJustification: 'Prefix-width family',
    expectedFalsePositives: 'Doc fixtures',
    expectedFalseNegatives: 'Rotated formats',
    positiveExamples: ['ghu_abcdefghijklmnopqrstuvwxyz0123456789'],
  }),
  spec({
    id: 'github.server_to_server_ghs',
    name: 'GitHub server-to-server token (ghs_)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bghs_[A-Za-z0-9]{36}\b`,
    confidence: 0.95,
    sourceRef: 'GitHub token prefix ghs_',
    regexJustification: 'Prefix-width family',
    expectedFalsePositives: 'Doc fixtures',
    expectedFalseNegatives: 'Rotated formats',
    positiveExamples: ['ghs_abcdefghijklmnopqrstuvwxyz0123456789'],
  }),
  spec({
    id: 'github.refresh_ghr',
    name: 'GitHub refresh token (ghr_)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bghr_[A-Za-z0-9_]{36,}\b`,
    confidence: 0.93,
    sourceRef: 'GitHub token prefix ghr_',
    regexJustification: 'ghr_ refresh family (variable body)',
    expectedFalsePositives: 'Unrelated ghr_ product codes',
    expectedFalseNegatives: 'Strict-width-only tokens if GitHub tightens',
    positiveExamples: ['ghr_abcdefghijklmnopqrstuvwxyz0123456789AB'],
  }),
  spec({
    id: 'gitlab.pat',
    name: 'GitLab personal access token (glpat-)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bglpat-[A-Za-z0-9\-_]{20,}\b`,
    confidence: 0.95,
    sourceRef: 'GitLab PAT prefix glpat-',
    regexJustification: 'Stable vendor prefix',
    expectedFalsePositives: 'Examples in GitLab docs',
    expectedFalseNegatives: 'Older tokens without glpat-',
    positiveExamples: ['glpat-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'gitlab.runner_token',
    name: 'GitLab runner token (glrt-)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bglrt-[A-Za-z0-9\-_]{20,}\b`,
    confidence: 0.94,
    sourceRef: 'GitLab runner token prefix',
    regexJustification: 'glrt- prefix',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Legacy runner registration tokens',
    positiveExamples: ['glrt-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'gitlab.agent_token',
    name: 'GitLab agent token (glagent-)',
    category: 'vcs',
    severity: 'critical',
    pattern: String.raw`\bglagent-[A-Za-z0-9\-_]{20,}\b`,
    confidence: 0.94,
    sourceRef: 'GitLab agent token prefix',
    regexJustification: 'glagent- prefix',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Custom agent issuers',
    positiveExamples: ['glagent-abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'bitbucket.atbb',
    name: 'Bitbucket app password / token (ATBB)',
    category: 'vcs',
    severity: 'high',
    pattern: String.raw`\bATBB[A-Za-z0-9]{32,}\b`,
    confidence: 0.88,
    sourceRef: 'Bitbucket Cloud token prefix ATBB (observed public scanner rules)',
    regexJustification: 'ATBB vendor-like prefix',
    expectedFalsePositives: 'Unrelated ATBB product IDs',
    expectedFalseNegatives: 'Non-ATBB Bitbucket credentials',
    positiveExamples: [`ATBB${'a'.repeat(40)}`],
  }),
  spec({
    id: 'npm.access_token',
    name: 'npm access token (npm_)',
    category: 'ci_cd',
    severity: 'critical',
    pattern: String.raw`\bnpm_[A-Za-z0-9]{36}\b`,
    confidence: 0.95,
    sourceRef: 'npm token prefix npm_',
    regexJustification: 'npm_ + 36',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Legacy UUID npm tokens',
    positiveExamples: ['npm_abcdefghijklmnopqrstuvwxyz0123456789'],
  }),
  spec({
    id: 'pypi.api_token',
    name: 'PyPI API token (pypi-)',
    category: 'ci_cd',
    severity: 'critical',
    pattern: String.raw`\bpypi-[A-Za-z0-9_\-]{20,}\b`,
    confidence: 0.93,
    sourceRef: 'PyPI API token prefix',
    regexJustification: 'pypi- prefix',
    expectedFalsePositives: 'Package name collisions unlikely with long body',
    expectedFalseNegatives: 'User/pass uploads',
    positiveExamples: ['pypi-AgEIcHlwaS5vcmcAAAAAAAAAA'],
  }),
  spec({
    id: 'huggingface.token',
    name: 'Hugging Face token (hf_)',
    category: 'ci_cd',
    severity: 'high',
    pattern: String.raw`\bhf_[A-Za-z0-9]{20,}\b`,
    confidence: 0.9,
    sourceRef: 'Hugging Face access token prefix hf_',
    regexJustification: 'hf_ prefix',
    expectedFalsePositives: 'Short hf_ codes',
    expectedFalseNegatives: 'Older tokens',
    positiveExamples: ['hf_abcdefghijklmnopqrstuvwxyz'],
  }),
  spec({
    id: 'circleci.token_label',
    name: 'CircleCI token assignment',
    category: 'ci_cd',
    severity: 'high',
    pattern: String.raw`(?:CIRCLECI_TOKEN|CIRCLE_TOKEN)\s*[=:]\s*['"]?[A-Za-z0-9]{20,}`,
    confidence: 0.9,
    sourceRef: 'CircleCI env var names',
    regexJustification: 'Labeled env assignment',
    expectedFalsePositives: 'README examples',
    expectedFalseNegatives: 'Unlabeled tokens',
    positiveExamples: ['CIRCLE_TOKEN=abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'travis.token_label',
    name: 'Travis CI token assignment',
    category: 'ci_cd',
    severity: 'high',
    pattern: String.raw`(?:TRAVIS_TOKEN|travis_api_token)\s*[=:]\s*['"]?[A-Za-z0-9_\-]{20,}`,
    confidence: 0.88,
    sourceRef: 'Travis CI token env naming',
    regexJustification: 'Labeled assignment',
    expectedFalsePositives: 'Docs',
    expectedFalseNegatives: 'Unlabeled',
    positiveExamples: ['TRAVIS_TOKEN=abcdefghijklmnopqrstuv'],
  }),
  spec({
    id: 'digitalocean.pat',
    name: 'DigitalOcean PAT (dop_v1_)',
    category: 'ci_cd',
    severity: 'critical',
    pattern: String.raw`\bdop_v1_[a-f0-9]{64}\b`,
    confidence: 0.96,
    sourceRef: 'DigitalOcean personal access token prefix',
    regexJustification: 'dop_v1_ + 64 hex',
    expectedFalsePositives: 'Extremely rare',
    expectedFalseNegatives: 'Legacy DO tokens',
    positiveExamples: [`dop_v1_${'ab'.repeat(32)}`],
  }),
];
